name: update blog

on:
  schedule:
    - cron: '0 23 * * 2'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@v3.1.0
      with:
        submodules: true
        repository: fuhrerh-lemon/blog-source
        
    - name: update source-blog
      run: |
        cd source
        rm -rf _posts
        git clone https://github.com/HewelFo/backup.post-blog-.git _posts
        cd ..
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3.8.2
      with:
        delete-branch: true
        branch: update-source-blog
        token: ${{ secrets.GH_TOKEN }}
